domains:
- domain: geo.rfc2549.network
  ttl: 10
  records:
    geo.rfc2549.network:
      - soa: ns1.geo.rfc2549.network ns.geo.rfc2549.network 2014090125 7200 3600 1209600 3600
      - soa: ns2.geo.rfc2549.network ns.geo.rfc2549.network 2014090125 7200 3600 1209600 3600
      - ns: ns1.geo.rfc2549.network
      - ns: ns2.geo.rfc2549.network
      - a: 185.187.152.2
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::c
      - aaaa: 2a05:b0c4:1::d
    ns1.geo.rfc2549.network:
      - a: 185.187.152.2
      - aaaa: 2a05:b0c4:1::c
    ns2.geo.rfc2549.network:
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::d
    
    debug.geo.rfc2549.network:
      - txt: "ip %ip %af city %ci country %cc %co state %cn region %re name %na as %as"
    info.geo.rfc2549.network:
      - txt: "ip %ip %af city %ci country %cc %co state %cn region %re name %na as %as"
    anycast.geo.rfc2549.network:
      - a: 185.187.152.2
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::c
      - aaaa: 2a05:b0c4:1::d


#MORDOR
    #north america
    na.mordor.geo.rfc2549.network:
      - cname: montreal.mordor.rfc2549.network

    #south america
    sa.mordor.geo.rfc2549.network:
      - cname: montreal.mordor.rfc2549.network
      - cname: frankfurt.mordor.rfc2549.network

    #europe
    eu.mordor.geo.rfc2549.network:
      - cname: frankfurt.mordor.rfc2549.network

    #asia
    as.mordor.geo.rfc2549.network:
      - cname: frankfurt.mordor.rfc2549.network
      - cname: singapore.mordor.rfc2549.network

    #oceania
    oc.mordor.geo.rfc2549.network:
      - cname: singapore.mordor.rfc2549.network

    #africa
    af.mordor.geo.rfc2549.network:
      - cname: frankfurt.mordor.rfc2549.network

    #antartica
    an.mordor.geo.rfc2549.network:
      - cname: frankfurt.mordor.rfc2549.network
      - cname: montreal.mordor.rfc2549.network


#GONDOR


#ISENGARD

# geo continents
    #north america
    na.geo.rfc2549.network:
      - cname: montreal.isengard.rfc2549.network
      - cname: newyork.isengard.rfc2549.network
      - cname: sanfrancisco.isengard.rfc2549.network

    #south america
    sa.geo.rfc2549.network:
      - cname: montreal.isengard.rfc2549.network
      - cname: newyork.isengard.rfc2549.network
      - cname: sanfrancisco.isengard.rfc2549.network

    #europe
    eu.geo.rfc2549.network:
      - cname: frankfurt.isengard.rfc2549.network

    #asia
    as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
      - cname: mumbai.isengard.rfc2549.network

    #oceania
    oc.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
      - cname: sydney.isengard.rfc2549.network

    #africa
    af.geo.rfc2549.network:
      - cname: frankfurt.isengard.rfc2549.network

    #antartica
    an.geo.rfc2549.network:
      - cname: frankfurt.isengard.rfc2549.network

# asian optimizations
    sg.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    in.as.geo.rfc2549.network:
      - cname: mumbai.isengard.rfc2549.network
    lk.as.geo.rfc2549.network:
      - cname: mumbai.isengard.rfc2549.network
    np.as.geo.rfc2549.network:
      - cname: mumbai.isengard.rfc2549.network
    bd.as.geo.rfc2549.network:
      - cname: mumbai.isengard.rfc2549.network
    pk.as.geo.rfc2549.network:
      - cname: mumbai.isengard.rfc2549.network
    bt.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    mm.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    mn.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    th.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    la.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    kh.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    vn.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    my.as.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network

# oceanic optimizations
    au.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    nz.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    nc.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    vu.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    nu.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    ws.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    to.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    nr.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    pg.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    fj.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    ck.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    pn.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    mh.oc.geo.rfc2549.network:
      - cname: sydney.isengard.rfc2549.network
    tw.oc.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    kr.oc.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network
    kp.oc.geo.rfc2549.network:
      - cname: singapore.isengard.rfc2549.network

# services
  services:
    isengard.geo.rfc2549.network:
      default: ['%as.geo.rfc2549.network', '%re.%cc.%cn.geo.rfc2549.network', '%cc.%cn.geo.rfc2549.network', '%cn.geo.rfc2549.network', 'eu.isengard.rfc2549.network']
    mordor.geo.rfc2549.network:
      default: ['%as.mordor.geo.rfc2549.network', '%re.%cc.%cn.mordor.geo.rfc2549.network', '%cc.%cn.mordor.geo.rfc2549.network', '%cn.mordor.geo.rfc2549.network', 'eu.mordor.geo.rfc2549.network']
