domains:
- domain: geo.rfc2549.network
  ttl: 10
  records:
    geo.rfc2549.network:
      - soa: ns1.geo.rfc2549.network ns.geo.rfc2549.network 2014090125 7200 3600 1209600 3600
      - soa: ns2.geo.rfc2549.network ns.geo.rfc2549.network 2014090125 7200 3600 1209600 3600
      - ns: ns1.geo.rfc2549.network
      - ns: ns2.geo.rfc2549.network
      - a: 185.187.152.2
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::c
      - aaaa: 2a05:b0c4:1::d
    ns1.geo.rfc2549.network:
      - a: 185.187.152.2
      - aaaa: 2a05:b0c4:1::c
    ns2.geo.rfc2549.network:
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::d
    
    debug.geo.rfc2549.network:
      - txt: "ip %ip %af city %ci country %cc %co state %cn region %re name %na as %as"
    info.geo.rfc2549.network:
      - txt: "ip %ip %af city %ci country %cc %co state %cn region %re name %na as %as"
    anycast.geo.rfc2549.network:
      - a: 185.187.152.2
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::c
      - aaaa: 2a05:b0c4:1::d


#MORDOR
    #north america
    na.mordor.geo.rfc2549.network:
      # montreal
      - a: 15.235.82.144
      - a: 192.95.37.236
      - aaaa: 2607:5300:203:a890:bbbb:cafe:dead:beef
      - aaaa: 2607:5300:203:a890:bbbb:feed:dead:beef

    #south america
    sa.mordor.geo.rfc2549.network:
      # montreal
      - a: 15.235.82.144
      - a: 192.95.37.236
      - aaaa: 2607:5300:203:a890:bbbb:cafe:dead:beef
      - aaaa: 2607:5300:203:a890:bbbb:feed:dead:beef
      # frankfurt
      - a: 141.95.31.133
      - a: 51.89.14.47
      - a: 162.19.139.93
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef

    #europe
    eu.mordor.geo.rfc2549.network:
      # frankfurt
      - a: 141.95.31.133
      - a: 51.89.14.47
      - a: 162.19.139.93
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef

    #asia
    as.mordor.geo.rfc2549.network:
      # frankfurt
      - a: 141.95.31.133
      - a: 51.89.14.47
      - a: 162.19.139.93
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef

    #oceania
    oc.mordor.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef

    #africa
    af.mordor.geo.rfc2549.network:
      # frankfurt
      - a: 141.95.31.133
      - a: 51.89.14.47
      - a: 162.19.139.93
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef

    #antartica
    an.mordor.geo.rfc2549.network:
      # montreal
      - a: 15.235.82.144
      - a: 192.95.37.236
      - aaaa: 2607:5300:203:a890:bbbb:cafe:dead:beef
      - aaaa: 2607:5300:203:a890:bbbb:feed:dead:beef
      # frankfurt
      - a: 141.95.31.133
      - a: 51.89.14.47
      - a: 162.19.139.93
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef


#GONDOR


#ISENGARD

# geo continents
    #north america
    na.geo.rfc2549.network:
      # montreal
      - a: 15.235.82.144
      - a: 192.95.37.236
      - aaaa: 2607:5300:203:a890:bbbb:cafe:dead:beef
      - aaaa: 2607:5300:203:a890:bbbb:feed:dead:beef
      # newyork
      - a: 162.216.17.80
      - aaaa: 2600:3c03::f03c:93ff:fe0a:66ad
      # sanfrancisco
      - a: 45.56.90.100
      - aaaa: 2600:3c01::f03c:93ff:fe0a:af57

    #south america
    sa.geo.rfc2549.network:
      # montreal
      - a: 15.235.82.144
      - a: 192.95.37.236
      - aaaa: 2607:5300:203:a890:bbbb:cafe:dead:beef
      - aaaa: 2607:5300:203:a890:bbbb:feed:dead:beef
      # newyork
      - a: 162.216.17.80
      - aaaa: 2600:3c03::f03c:93ff:fe0a:66ad
      # sanfrancisco
      - a: 45.56.90.100
      - aaaa: 2600:3c01::f03c:93ff:fe0a:af57

    #europe
    eu.geo.rfc2549.network:
      # frankfurt
      - a: 162.19.139.93
      - a: 141.95.31.133
      - a: 51.89.14.47
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef

    #asia
    as.geo.rfc2549.network:
      # mumbai
      - a: 172.105.252.174
      - a: 172.104.207.123
      - aaaa: 2400:8904::f03c:93ff:fe0a:af02
      - aaaa: 2400:8904::f03c:93ff:fe48:fea
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef

    #oceania
    oc.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65

    #africa
    af.geo.rfc2549.network:
      # frankfurt
      - a: 162.19.139.93
      - a: 141.95.31.133
      - a: 51.89.14.47
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef

    #antartica
    an.geo.rfc2549.network:
      # frankfurt
      - a: 162.19.139.93
      - a: 141.95.31.133
      - a: 51.89.14.47
      - aaaa: 2001:41d0:700:6b5d:aaaa:cafe:dead:beef
      - aaaa: 2001:41d0:700:6b5d:aaaa:feed:dead:beef
      # montreal
      - a: 15.235.82.144
      - a: 192.95.37.236
      - aaaa: 2607:5300:203:a890:bbbb:cafe:dead:beef
      - aaaa: 2607:5300:203:a890:bbbb:feed:dead:beef
      # newyork
      - a: 162.216.17.80
      - aaaa: 2600:3c03::f03c:93ff:fe0a:66ad

# asian optimizations
    sg.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    in.as.geo.rfc2549.network:
      # mumbai
      - a: 172.105.252.174
      - a: 172.104.207.123
      - aaaa: 2400:8904::f03c:93ff:fe0a:af02
      - aaaa: 2400:8904::f03c:93ff:fe48:fea
    lk.as.geo.rfc2549.network:
      # mumbai
      - a: 172.105.252.174
      - a: 172.104.207.123
      - aaaa: 2400:8904::f03c:93ff:fe0a:af02
      - aaaa: 2400:8904::f03c:93ff:fe48:fea
    np.as.geo.rfc2549.network:
      # mumbai
      - a: 172.105.252.174
      - a: 172.104.207.123
      - aaaa: 2400:8904::f03c:93ff:fe0a:af02
      - aaaa: 2400:8904::f03c:93ff:fe48:fea
    bd.as.geo.rfc2549.network:
      # mumbai
      - a: 172.105.252.174
      - a: 172.104.207.123
      - aaaa: 2400:8904::f03c:93ff:fe0a:af02
      - aaaa: 2400:8904::f03c:93ff:fe48:fea
    pk.as.geo.rfc2549.network:
      # mumbai
      - a: 172.105.252.174
      - a: 172.104.207.123
      - aaaa: 2400:8904::f03c:93ff:fe0a:af02
      - aaaa: 2400:8904::f03c:93ff:fe48:fea
    bt.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    mm.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    mn.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    th.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    la.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    kh.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    vn.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    my.as.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef

# oceanic optimizations
    au.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    nz.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    nc.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    vu.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    nu.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    ws.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    to.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    nr.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    pg.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    fj.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    ck.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    pn.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    mh.oc.geo.rfc2549.network:
      # sydney
      - a: 194.195.123.64
      - aaaa: 2400:8907::f03c:93ff:fe0a:af65
    tw.oc.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    kr.oc.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef
    kp.oc.geo.rfc2549.network:
      # singapore
      - a: 15.235.144.61
      - a: 139.99.30.177
      - aaaa: 2402:1f00:8001:133d:cccc:cafe:dead:beef
      - aaaa: 2402:1f00:8001:133d:cccc:feed:dead:beef

# services
  services:
    isengard.geo.rfc2549.network:
      default: ['%as.geo.rfc2549.network', '%re.%cc.%cn.geo.rfc2549.network', '%cc.%cn.geo.rfc2549.network', '%cn.geo.rfc2549.network', 'eu.isengard.rfc2549.network']
    mordor.geo.rfc2549.network:
      default: ['%as.mordor.geo.rfc2549.network', '%re.%cc.%cn.mordor.geo.rfc2549.network', '%cc.%cn.mordor.geo.rfc2549.network', '%cn.mordor.geo.rfc2549.network', 'eu.mordor.geo.rfc2549.network']
