domains:
- domain: geo.rfc2549.network
  ttl: 10
  records:
    geo.rfc2549.network:
      - soa: ns1.geo.rfc2549.network ns.geo.rfc2549.network 2014090125 7200 3600 1209600 3600
      - soa: ns2.geo.rfc2549.network ns.geo.rfc2549.network 2014090125 7200 3600 1209600 3600
      - ns: ns1.geo.rfc2549.network
      - ns: ns2.geo.rfc2549.network
      - a: 185.187.152.2
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::c
      - aaaa: 2a05:b0c4:1::d
    ns1.geo.rfc2549.network:
      - a: 185.187.152.2
      - aaaa: 2a05:b0c4:1::c
    ns2.geo.rfc2549.network:
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::d
    
    debug.geo.rfc2549.network:
      - txt: "ip %ip %af city %ci country %cc %co state %cn region %re name %na as %as"
    info.geo.rfc2549.network:
      - txt: "ip %ip %af city %ci country %cc %co state %cn region %re name %na as %as"
    anycast.geo.rfc2549.network:
      - a: 185.187.152.2
      - a: 185.187.153.2
      - aaaa: 2a05:b0c4:1::c
      - aaaa: 2a05:b0c4:1::d



#NCSA
    ncsa.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    us-west.ncsa.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    us-east.ncsa.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    latam.ncsa.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef

#EMEA
    emea.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    euro.emea.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    africa.emea.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    meast.emea.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef

#APAC
    apac.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    west-asia.apac.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    east-asia.apac.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    south-asia.apac.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    west-oceania.apac.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    south-oceania.apac.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef
    north-oceania.apac.geo.rfc2549.network:
      # strasbourg
      - a: 51.91.152.156
      - aaaa: 2001:41d0:0403:2f9c:cccc:feed:dead:beef


# geo continents
    #north america
    na.geo.geo.rfc2549.network:
      - cname: east.ncsa.geo.rfc2549.network
      - cname: west.ncsa.geo.rfc2549.network

    #south america
    sa.geo.geo.rfc2549.network:
      - cname: latam.ncsa.geo.rfc2549.network

    #europe
    eu.geo.geo.rfc2549.network:
      - cname: euro.emea.geo.rfc2549.network

    #asia
    as.geo.geo.rfc2549.network:
      - cname: west-asia.apac.geo.rfc2549.network

    #oceania
    oc.geo.geo.rfc2549.network:
      - cname: west-oceania.apac.geo.rfc2549.network

    #africa
    af.geo.geo.rfc2549.network:
      - cname: africa.emea.geo.rfc2549.network

    #antartica
    an.geo.geo.rfc2549.network:
      - cname: emea.geo.rfc2549.network

# asian optimizations
    sg.as.geo.geo.rfc2549.network:
      - cname: west-oceania.apac.geo.rfc2549.network
    in.as.geo.geo.rfc2549.network:
      - cname: south-asia.apac.geo.rfc2549.network
    lk.as.geo.geo.rfc2549.network:
      - cname: south-asia.apac.geo.rfc2549.network
    np.as.geo.geo.rfc2549.network:
      - cname: south-asia.apac.geo.rfc2549.network
    bd.as.geo.geo.rfc2549.network:
      - cname: south-asia.apac.geo.rfc2549.network
    pk.as.geo.geo.rfc2549.network:
      - cname: south-asia.apac.geo.rfc2549.network
    bt.as.geo.geo.rfc2549.network:
      - cname: east-asia.apac.geo.rfc2549.network
    mm.as.geo.geo.rfc2549.network:
      - cname: east-asia.apac.geo.rfc2549.network
    mn.as.geo.geo.rfc2549.network:
      - cname: east-asia.apac.geo.rfc2549.network
    th.as.geo.geo.rfc2549.network:
      - cname: east.apac.geo.rfc2549.network
    la.as.geo.geo.rfc2549.network:
      - cname: east-asia.apac.geo.rfc2549.network
    kh.as.geo.geo.rfc2549.network:
      - cname: east-asia.apac.geo.rfc2549.network
    vn.as.geo.geo.rfc2549.network:
      - cname: east-asia.apac.geo.rfc2549.network
    my.as.geo.geo.rfc2549.network:
      - cname: east-asia.apac.geo.rfc2549.network

# oceanic optimizations
    au.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    nz.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    nc.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    vu.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    nu.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    ws.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    to.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    nr.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    pg.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    fj.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    ck.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    pn.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    mh.oc.geo.geo.rfc2549.network:
      - cname: south-oceania.apac.geo.rfc2549.network
    tw.oc.geo.geo.rfc2549.network:
      - cname: north-oceania.apac.geo.rfc2549.network
    kr.oc.geo.geo.rfc2549.network:
      - cname: north-oceania.apac.geo.rfc2549.network
    kp.oc.geo.geo.rfc2549.network:
      - cname: north-oceania.apac.geo.rfc2549.network

# services
  services:
    director.geo.rfc2549.network:
      default: ['%as.geo.geo.rfc2549.network', '%re.%cc.%cn.geo.geo.rfc2549.network', '%cc.%cn.geo.geo.rfc2549.network', '%cn.geo.geo.rfc2549.network', 'emea.geo.rfc2549.network']
    core.geo.rfc2549.network:
      default: ['%as.geo.geo.rfc2549.network', '%re.%cc.%cn.geo.geo.rfc2549.network', '%cc.%cn.geo.geo.rfc2549.network', '%cn.geo.geo.rfc2549.network', 'emea.geo.rfc2549.network']
    edge.geo.rfc2549.network:
      default: ['%as.geo.geo.rfc2549.network', '%re.%cc.%cn.geo.geo.rfc2549.network', '%cc.%cn.geo.geo.rfc2549.network', '%cn.geo.geo.rfc2549.network', 'emea.geo.rfc2549.network']